{% set name = "pycocoevalcap" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycocoevalcap-{{ version }}.tar.gz
  sha256: 7857f4d596ca2fa0b1a9a3c2067588a4257556077b7ad614d00b2b7b8f57cdde

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - pycocotools >=2.0.2

test:
  imports:
    - pycocoevalcap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/salaniz/pycocoevalcap
  summary: MS-COCO Caption Evaluation for Python 3
  license: MIT AND BSD-2-Clause
  license_file:
    - license.txt
    - LICENSE

extra:
  recipe-maintainers:
    - piterand
